# rubocop styles

Style/HashSyntax:
  EnforcedStyle: hash_rockets
  UseHashRocketsWithSymbolValues: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# Ignore config
AllCops:
  Exclude:
    - spec/spec_helper.rb

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

# aruba depends on strings not being frozen
Style/FrozenStringLiteralComment:
  Exclude:
    - "spec/cli_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/*.rb"

# Command names
Naming/MethodName:
  Exclude:
    - "lib/cli.rb"
