# rubocop styles

Style/HashSyntax:
  EnforcedStyle: hash_rockets
  UseHashRocketsWithSymbolValues: true
  PreferHashRocketsForNonAlnumEndingSymbols: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

AllCops:
  Exclude:
    - spec/spec_helper.rb

Naming/MethodName:
  Exclude:
    - "lib/cli.rb"

Style/FrozenStringLiteralComment:
  Exclude:
    - "spec/cli_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/cli_spec.rb"
